name: LaunchingTest
'on':
  workflow_dispatch: null
  schedule:
  - cron: 40 13 * * 2
jobs:
  trace_job:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Job-activated, event -> ${{ github.event_name }}"
  gen_baseline_job:
    if: ${{ github.repository_owner == 'd8bkqc5q' && (github.event_name == 'workflow_dispatch'
      || github.event_name == 'schedule') }}
    runs-on: ubuntu-latest
    steps:
    - run: echo "Job-activated, event -> ${{ github.event_name }}"
  gen_ensemble_job:
    needs: gen_baseline_job
    runs-on: ubuntu-latest
    steps:
    - run: echo "gen_ensemble_job"
